name: Deploy to Server

on:
  push:
    branches:
      - v4

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Build Project
        run: |
          npm install -g npm@latest
          npm install
          npx quartz build

      - name: Deploy static files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "public/*"
          target: "/root/quartz/public"
          strip_components: 1

      - name: Refresh Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 直接托管已经传过去的静态文件夹，不再 build
            pm2 serve /root/quartz/public 6066 --name "quartz-medical"
            pm2 save