name: Deploy to Server

on:
  push:
    branches:
      - v4

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - name: Build Project
        run: |
          npm install -g npm@latest
          npm install
          npx quartz build

      - name: Deploy static files via SCP
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "public/*"
          target: "/root/quartz-web"
          strip_components: 1

      - name: Refresh Server
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            pm2 restart "quartz-medical" || pm2 start "npx quartz build --serve --port 6066" --name "quartz-medical"